AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: refine-temp-api

Globals:
  Function:
    Timeout: 10
    MemorySize: 256
    Tracing: Active

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,Origin,Accept'"
        AllowOrigin: "'*'"

  AppFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      BuildProperties:
        GoBuildFlags: -tags lambda.norpc
    Properties:
      CodeUri: cmd/lambda
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures: [x86_64]   
      Events:
        Root:
          Type: Api
          Properties: { Path: /,               Method: GET,  RestApiId: !Ref Api }
        Health:
          Type: Api
          Properties: { Path: /health,         Method: GET,  RestApiId: !Ref Api }
        Problems:
          Type: Api
          Properties: { Path: /api/problems,   Method: POST, RestApiId: !Ref Api }
        Validate:
          Type: Api
          Properties: { Path: /api/validate,   Method: POST, RestApiId: !Ref Api }
        Emails:
          Type: Api
          Properties: { Path: /emails,         Method: POST, RestApiId: !Ref Api }

Outputs:
  ApiUrl:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod"
